name: Generate Contribution Graphs

on:
  schedule:
    # Runs every 6 hours (more frequent updates)
    - cron: "0 */6 * * *"
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  generate_graphs:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Generate Snake animation
      - name: Generate Snake
        uses: Platane/snk@master
        id: snake
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg?palette=github-dark
            dist/snake.gif

      # Step 3: Generate Pacman animation (using alternative working action)
      - name: Generate Pacman
        uses: marcelofernandes/pacman-contributions@main
        id: pacman
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/pacman.svg
            dist/pacman-dark.svg

      # Step 4: Verify generated files
      - name: List generated files
        run: |
          ls -la dist/
          echo "Files generated successfully!"

      # Step 5: Deploy to output branch
      - name: Deploy to GitHub Pages
        uses: peaceiris/gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
          keep_files: false
          commit_message: "Update contribution graphs - [skip ci]"
