# GitHub Action for generating animated contribution graphs (Snake + Pacman)
name: Generate Contribution Graphs

# Controls when the action will run:
on:
  schedule:
    # Runs every 12 hours (UTC)
    - cron: "0 */12 * * *"
  
  # Manual trigger from Actions tab
  workflow_dispatch:
  
  # Run on every push to main branch
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # ==================== STEP 1: CHECKOUT REPO ====================
      - name: Clone repository
        uses: actions/checkout@v3

      # ==================== STEP 2: GENERATE SNAKE GRAPH ====================
      - name: Generate Snake Animation
        uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
            dist/github-contribution-grid-snake.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # ==================== STEP 3: GENERATE PACMAN GRAPH ====================
      - name: Generate Pacman Animation
        uses: PlamenaRadneva/pacman-contributions@v1.0.0
        id: pacman-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/pacman-contribution-graph.svg
            dist/pacman-contribution-graph-dark.svg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # ==================== STEP 4: VERIFY GENERATED FILES ====================
      - name: List generated files
        run: |
          ls -la dist/
          echo "Files generated successfully!"

      # ==================== STEP 5: DEPLOY TO OUTPUT BRANCH ====================
      - name: Push generated files
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output  # Branch where SVGs will be stored
          build_dir: dist       # Directory containing generated files
          commit_message: "Update contribution graphs - [skip ci]"
          keep_files: false     # Overwrite existing files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
