name: Generate Pacman Animation

on:
  schedule:
    - cron: "0 */12 * * *" # Berjalan setiap 12 jam
  workflow_dispatch:

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Generate pacman-contribution-graph.svg
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}
          # Action ini akan membuat file 'pacman-contribution-graph.svg' di root

      - name: Prepare build directory
        # Membuat folder 'dist' dan memindahkan file pacman ke dalamnya
        run: |
          mkdir -p dist
          mv pacman-contribution-graph.svg dist/

      - name: Push pacman image to the output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist # Hanya folder 'dist' yang akan di-push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
