name: Generate Pacman Animation

on:
  schedule:
    - cron: "0 */12 * * *" # Berjalan setiap 12 jam
  workflow_dispatch:

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate pacman images
        # Menggunakan action yang terbukti andal untuk mode terang/gelap
        uses: maurodesouz/profile-pacman-contributions@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Path harus diawali dengan folder `dist` agar sesuai dengan build_dir
          output_path_light: dist/pacman-contribution-graph.svg
          output_path_dark: dist/pacman-contribution-graph-dark.svg

      - name: Push pacman images to the output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist # Hanya folder 'dist' yang akan di-push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
