name: Generate Pacman Contribution Graph

on:
  # Jalankan workflow ini setiap hari pada tengah malam (00:00 UTC)
  schedule:
    - cron: '0 0 * * *'
  # Izinkan untuk menjalankan workflow ini secara manual dari tab Actions
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate pacman contribution graph
        uses: maurodesouz/profile-pacman-contributions@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Path untuk menyimpan file SVG versi terang
          output_path_light: output/pacman-contribution-graph.svg
          # Path untuk menyimpan file SVG versi gelap
          output_path_dark: output/pacman-contribution-graph-dark.svg

      - name: Commit and push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "feat: update pacman contribution graph" || exit 0
          git push
